### ISSUE TITLE
502 Bad gateway

### ISSUE THREAD

**Issue by Dirowa** [hexylena/code-combat-client#1]
Hi @hexylena

Please only respond to this when you feel free and wants too.
We have encounterd an error with the tgco . Bad gateway 502

I noticed in the Nginx Journal the following error.
```
Dec 12 16:00:10 cocalc.atgm.avans.nl nginx[576759]: cocalc.atgm.avans.nl nginx: 2022/12/12 16:00:10 [error] 576759#576759: *2737 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.2, server: cocalc.atgm.avans.nl, request: "POST /the-great-code-off/ HTTP/1.1", upstream: "http://127.0.0.1:9091/the-great-code-off/", host: "cocalc.atgm.avans.nl"
```

Do you perhaps know what the next step it to see where it is going wrong. i dont really dare to play with the code or nginx settings yet. 

I did check the Netstat but i wasnt able to find tgco mentioned in it, any clues?

**Comment by hexylena** [comment]
we never deployed it properly. it was running under a bash script in my
account. someone just needs to write a systemd unit at minimum to keep it
running. ansibke would be nice but, not necessary

**Comment by Dirowa** [comment]
once I get it working. shall I try to make it a public ansible module for cocalc servers?

**Comment by hexylena** [comment]
that'd be super cool!

**Comment by Dirowa** [comment]
Just incase i,m being a silly person.

But for some reason does the command ``` gunicorn performance.wsgi --bind 127.0.0.1:9091 ``` -> functional way better then using ``` python manage.py runserver 9091 ```. do you perhaps know why?

the manage.py is way slower and has nonreproducible graph output ( graphs missing, weird layout, fonts overlapping). but it is still a bit slow (* note, never had to wait for results so i,m not sure what normal waiting times are ( it is now 14 seconds )).

Am i using the wrong commands  or is there something else?
The internet at Avans is currently weak the recent weeks.

**Comment by hexylena** [comment]
Yeah, gunicorn is written as a high performance webserver. `manager.py` is something written in pure python that they can ship with django, but it is never meant for production.

The graphs should generate in <1s, if it's more, that's odd.

**Comment by Dirowa** [comment]
Finialised the ansible role for the server side
https://github.com/Dirowa/the-great-code-off-server_ansible

I wasnt able to create a sqlite3 db easily with sqlite3 so i cleaned the api_entry and uploaded that on github.
Further i did notice the secret_key but i wasn't able to find where it was connected to, any clues?

Anyhow if you have any suggestions/ edit etc please let me know

**Comment by hexylena** [comment]
you don't need to create the dB, running python maNage.py migrate will do
that for you + run necessary dB migrations.

re secret key, it should be set randomly per server.

**Comment by Dirowa** [comment]
hi @hexylena , i,m trying to finish the role. 
But i,m stuck with generating the Makefile.
For somereason the jinja template or generating the file doesn't comply with the tabs I give and will turn it into whitespace (which makefile absolutely doesnt like)

Any ideas for a way around this (already tried with various template files in jinja and generating directly with ansible)

**Comment by hexylena** [comment]
Could you link me to the code?

**Comment by Dirowa** [comment]
https://github.com/Dirowa/the-great-code-off-server_ansible/blob/main/tasks/main.yml link to the current task/main.yml.

The old template is still in templates but currently switch off

**Comment by hexylena** [comment]
I don't think you need a makefile there. If you need to run commands, just have ansible run them. Don't write out a makefile and then run that, that's not ideal.

Please see https://github.com/galaxyproject/ansible-tiaas2/blob/main/tasks/main.yml as comparison, there we use `django_manage` to: create the db, add a superuser, and do any relevant migrations.

**Comment by Dirowa** [comment]
Thank you for your help @hexylena , i wasn't aware such modules existed for ansible.
The Makefile is not nessacary anymore and a database will be deployed when there isn't one build yet.
The other commands are wrapped in the systemd.service

**Comment by hexylena** [comment]
awesome :)
